Exercise 3
cjarv4/DevOps-Course-Starter pull request #3
Opened 2020-09-23 10:24 UTC by cjarv4

2020-10-02 16:26 UTC, hugh-emerson requested changes
You've said you'll revisit this later, and that's fine - you can continue with later modules to keep in sync with the reading material and workshops. But to summarise what is needed to complete this module when you do have time:

- Fix the setup so it can work on other people's machines
-- Update the README with test requirements, instructions. Should also mention env vars. Almost every exercise will require updating the README.
-- Remove the geckodriver file path or make it relative
-- Add pytest and selenium to requirements.txt
-- Either update the README's instructions for running the app or fix the imports since you moved the python files into a todo_files subdirectory
- Fix the unit tests by mocking dependencies
- Fix the integration test by only fetching list ids after the app is created (this would also cause problems for the selenium test)
- Add at least some interaction with the webpage in the selenium test, followed by a meaningful assertion

2020-10-02 16:26 UTC, hugh-emerson commented on todo_files/tests/integration_test.py
> +import pytest
You need to add pytest & selenium to your project's dependencies (requirements.txt)

2020-10-02 16:26 UTC, hugh-emerson commented on todo_files/tests/test_app.py
> +    # os.environ["PATH"] += os.pathsep + '/Users/cjarv4/Downloads/'
You can delete this line

2020-10-02 16:26 UTC, hugh-emerson commented on todo_files/tests/test_app.py
> +    with webdriver.Firefox(executable_path=r'/Users/cjarv4/Downloads/geckodriver') as driver:
You should either make this a relative path or remove it

2020-10-02 16:26 UTC, hugh-emerson commented on todo_files/tests/unit_test.py
> +import Card as card
You should make the file lowercase `card.py` and then just `import card`

Same for the other modules.

2020-10-02 16:26 UTC, hugh-emerson commented on todo_files/tests/unit_test.py
> +    assert response=='5f3169dff2ad7b72d45fc4c3'
A unit test is meant to test a specific component in isolation. Any other systems/classes should be mocked:
When testing `trello.get_trello_board_id` you should be mocking `requests.get`
When testing `board.get_board_by_name` you should be mocking `trello.get_trello`

2020-10-02 16:26 UTC, hugh-emerson commented on todo_files/tests/integration_test.py
> +    assert old_show_all!=app.show_all_done
Your assertion should be checking the output of your app rather than an internal implementation detail.

If you want to test /showAll, you should assert that it changes the html response of a client.get('/') in the correct way.

2020-10-02 16:26 UTC, hugh-emerson commented on todo_files/tests/unit_test.py
> +    test_card = card.get_card_by_name(title)
A unit test shouldn't be creating real cards, and when you do something like this, you should make it a fixture that automatically cleans up after itself, instead of having to do `try`, `finally` in each test. (See the test_app fixture)

2020-10-02 16:26 UTC, hugh-emerson commented on todo_files/tests/unit_test.py
> +import Board as board
You should split unit tests into separate files for card, board, view_model and trello.

You can put them in a unit_tests directory so they're still grouped together.

2020-10-02 16:26 UTC, hugh-emerson commented on todo_files/Card.py
> +    return returnList
This function could live inside view_model.

2020-10-02 16:26 UTC, hugh-emerson commented on todo_files/Card.py
> +    def __init__(self, id, name, desc, due, last_activity):
Regarding the above code
```
toDoListId = trello.get_trello_list_id("To Do")
doingListId = trello.get_trello_list_id("Doing")	doingListId = trello.get_trello_list_id("Doing")
doneListId = trello.get_trello_list_id("Done")	doneListId = trello.get_trello_list_id("Done")
```

This is executed during import of the files. i.e. before your integration test can load .env.test
So your test is dependent on the app running for real and checks for those real list ids in `mock_get_cards`. That means the test isn't robust and also I can't run them for example.

2020-10-12 16:10 UTC, merged

2021-08-19 12:14 UTC, BenRamchandani commented
Putting a comment on here, though I've been looking at a few different branches to review this.

Currently:
* exercise-9 branch has a working unit test
* master branch has an integration test that looks about right, except that it does `find_dotenv('/.env.test')`
  * Should be `find_dotenv('.env.test')`
  * Your `.env.test` file should be at the top level (not in todo_files), and you've deleted it on the exercise-9 branch
  * This has been changed on the exercise-9 branch. It only works when it uses the real environment variables, because it doesn't mock anything
* exercise-9 branch has an e2e test which works, but it doesn't have any browser interaction

We'll need to see all the tests working in one place. I suggest you continue on top of the exercise-9 branch since you'll need to make changes to your integration tests after switching to Mongo.

To complete module 3 you'll need to:

* Finish the changes Hugh requested above
  * Update your README and .env.template files so there are working instructions to set up the .env file
  * Add at least some interaction with the webpage in the selenium test, followed by a meaningful assertion
* Update your integration test to mock out external dependencies (i.e. MongoDB. You could use [mongomock](https://pypi.org/project/mongomock/))